name: Deploy React-APP

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  B:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Install dependencies
        run: npm install /root/actions-runner/_work/GitHub-/GitHub-/


      - name: Build Node.js app
        run: npm run build

      - name: start react-app
        run: pm2 start npm --name "react-app" -- start
        
      - name: Send a mail on failure
        if: always()
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.gmail.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow finished
          body: Job  ${{job.status}}
          to: dvop.omer@gmail.com
          from: Github-action
     
        
